//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public Award()
        {
            this.Home_Front_workers_with_awards = new HashSet<Home_Front_workers_with_awards>();
        }
    
        public int ID { get; set; }
        public string Award_name { get; set; }
        public byte[] Photo_Awards { get; set; }
    
        public virtual ICollection<Home_Front_workers_with_awards> Home_Front_workers_with_awards { get; set; }
    }
}
