//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Front_workers
    {
        public Home_Front_workers()
        {
            this.Home_Front_workers_with_awards = new HashSet<Home_Front_workers_with_awards>();
            this.Home_Front_workers_position = new HashSet<Home_Front_workers_position>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string patronymic { get; set; }
        public string Birthdate { get; set; }
        public string Biography { get; set; }
        public byte[] Photo { get; set; }
        public string Date_of_the_beginning_of_work_in_Technical { get; set; }
        public string Ending_date { get; set; }
    
        public virtual ICollection<Home_Front_workers_with_awards> Home_Front_workers_with_awards { get; set; }
        public virtual ICollection<Home_Front_workers_position> Home_Front_workers_position { get; set; }
    }
}
