//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Home_front_workesEntities : DbContext
    {
        public Home_front_workesEntities()
            : base("name=Home_front_workesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Award> Awards { get; set; }
        public DbSet<Home_Front_workers> Home_Front_workers { get; set; }
        public DbSet<Home_Front_workers_with_awards> Home_Front_workers_with_awards { get; set; }
        public DbSet<Home_Front_workers_position> Home_Front_workers_position { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
