//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Home_Front_workers_position = new HashSet<Home_Front_workers_position>();
        }
    
        public int ID { get; set; }
        public string Experience { get; set; }
    
        public virtual ICollection<Home_Front_workers_position> Home_Front_workers_position { get; set; }
    }
}
